---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: add users, edit users, remove users, delete users 
summary: Añada usuarios al sistema Astra Control Center y elimine los usuarios que ya no tengan acceso al sistema. 
---
= Gestionar usuarios
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Puede añadir, eliminar y editar usuarios de la instalación de Astra Control Center mediante la interfaz de usuario de Astra Control Center. Puede utilizar la interfaz de usuario de Astra o. https://docs.netapp.com/us-en/astra-automation/index.html["La API de control Astra"^] para gestionar usuarios.



== Añadir usuarios

Los propietarios y administradores de cuentas pueden agregar más usuarios a la instalación de Astra Control Center.

.Pasos
. En el área de navegación *Administrar su cuenta*, seleccione *cuenta*.
. Seleccione la ficha *usuarios*.
. Seleccione *Agregar usuario*.
. Introduzca el nombre del usuario, la dirección de correo electrónico y una contraseña temporal.
+
El usuario deberá cambiar la contraseña en el primer inicio de sesión.

. Seleccione una función de usuario con los permisos de sistema adecuados.
+
Cada rol proporciona los siguientes permisos:

+
** Un *Visor* puede ver los recursos.
** Un *Miembro* tiene permisos de función de Viewer y puede administrar aplicaciones y clústeres, pero no puede anular la administración de aplicaciones o clústeres, ni eliminar instantáneas o copias de seguridad.
** Un *Admin* tiene permisos de rol de miembro y puede agregar y quitar cualquier otro usuario excepto el propietario.
** *Owner* tiene permisos de función de administrador y puede agregar y eliminar cualquier cuenta de usuario.


. Seleccione *Agregar*.




== Gestionar contraseñas

Puede gestionar las contraseñas de las cuentas de usuario en Astra Control Center.



=== Cambie la contraseña

Puede cambiar la contraseña de su cuenta de usuario en cualquier momento.

.Pasos
. Seleccione el icono Usuario situado en la parte superior derecha de la pantalla.
. Seleccione *Perfil*.
. Seleccione la lista desplegable *acciones* y seleccione *Cambiar contraseña*.
. Introduzca una contraseña que se ajuste a los requisitos de contraseña.
. Introduzca una vez más la contraseña para confirmarla.
. Seleccione *Cambiar contraseña*.




=== Restablecer la contraseña de otro usuario

Si su cuenta tiene permisos de rol de administrador o propietario, puede restablecer las contraseñas de otras cuentas de usuario así como las suyas propias. Al restablecer una contraseña, asigna una contraseña temporal que el usuario tendrá que cambiar al iniciar sesión.

.Pasos
. En el área de navegación *Administrar su cuenta*, seleccione *cuenta*.
. En la ficha *usuarios*, seleccione la lista desplegable en la columna *Estado* para el usuario.
. Seleccione *Restablecer contraseña*.
. Introduzca una contraseña temporal que cumpla los requisitos de contraseña.
. Introduzca una vez más la contraseña para confirmarla.
+

NOTE: La próxima vez que el usuario inicie sesión, se le solicitará que cambie la contraseña.

. Seleccione *Restablecer contraseña*.




== Cambiar el rol de un usuario

Los usuarios con el rol propietario pueden cambiar el rol de todos los usuarios, mientras que los usuarios con el rol Admin pueden cambiar el rol de los usuarios que tienen el rol Admin, Member o Viewer.

.Pasos
. En el área de navegación *Administrar su cuenta*, seleccione *cuenta*.
. En la ficha *usuarios*, seleccione la lista desplegable en la columna *rol* para el usuario.
. Seleccione una nueva función y, a continuación, seleccione *Cambiar rol* cuando se le solicite.


.Resultado
Astra Control Center actualiza los permisos del usuario en función de la nueva función que haya seleccionado.



== Quitar usuarios

Los usuarios con el rol propietario o administrador pueden eliminar otros usuarios de la cuenta en cualquier momento.

.Pasos
. En el área de navegación *Administrar su cuenta*, seleccione *cuenta*.
. En la ficha *usuarios*, seleccione la casilla de verificación en la fila de cada usuario que desee quitar.
. Seleccione *acciones* y seleccione *Eliminar usuario/s*.
. Cuando se le solicite, confirme la eliminación escribiendo la palabra "eliminar" y, a continuación, seleccione *Sí, Eliminar usuario*.


.Resultado
Astra Control Center elimina al usuario de la cuenta.
