---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore 
summary: Astra puede restaurar la configuración de sus aplicaciones y el almacenamiento persistente a partir de una copia Snapshot o una copia de seguridad. Los backups de almacenamiento persistente se transfieren del almacén de objetos, por lo que la restauración a partir de un backup existente se completará con la más rápida. 
---
= Restaurar aplicaciones
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control puede restaurar su aplicación a partir de una instantánea o una copia de seguridad. La restauración a partir de una snapshot existente será más rápida cuando se restaure la aplicación en el mismo clúster. Puede utilizar la interfaz de usuario de Astra Control o. https://docs.netapp.com/us-en/astra-automation/index.html["La API de control Astra"^] para restaurar aplicaciones.


NOTE: Si utiliza Helm para implantar aplicaciones, Astra Control Center requiere Helm versión 3. Se admite por completo la gestión y clonación de las aplicaciones implementadas con Helm 3 (o actualizadas de Helm 2 a Helm 3). Las aplicaciones implementadas con Helm 2 no son compatibles.


NOTE: Si restaura en un clúster diferente, asegúrese de que el clúster utilice el mismo modo de acceso de volumen persistente (por ejemplo, ReadWriteMany). Se producirá un error en la operación de restauración si el modo de acceso al volumen persistente de destino es diferente.

[NOTE]
====
Al crear un proyecto para alojar una aplicación en un clúster de OpenShift, se asigna un UID de SecurityContext al proyecto (o espacio de nombres de Kubernetes). Para habilitar Astra Control Center para proteger su aplicación y mover la aplicación a otro clúster o proyecto en OpenShift, debe agregar directivas que permitan que la aplicación se ejecute como cualquier UID. Por ejemplo, los siguientes comandos de la CLI de OpenShift otorgan las directivas adecuadas a una aplicación de WordPress.

`oc new-project wordpress`
`oc adm policy add-scc-to-group anyuid system:serviceaccounts:wordpress`
`oc adm policy add-scc-to-user privileged -z default -n wordpress`

====
.Pasos
. Seleccione *aplicaciones* y, a continuación, seleccione el nombre de una aplicación.
. Seleccione *Protección de datos*.
. Si desea restaurar desde una instantánea, mantenga seleccionado el icono *instantáneas*. De lo contrario, seleccione el icono *copias de seguridad* para restaurar desde una copia de seguridad.
. Seleccione la lista desplegable de la columna *acciones* para la instantánea o la copia de seguridad desde la que desea restaurar.
. Seleccione *Restaurar aplicación*.
. *Detalles de la restauración*: Especifique los detalles de la aplicación restaurada. De forma predeterminada, se muestran el clúster y el espacio de nombres actuales. Deje estos valores intactos para restaurar una aplicación in situ, que revierte la aplicación a una versión anterior de sí misma. Cambie estos valores si desea restaurar a un clúster o espacio de nombres diferentes.
+
** Introduzca un nombre y un espacio de nombres para la aplicación.
** Seleccione el clúster de destino de la aplicación.
** Seleccione *Revisión*.




. *Resumen de restauración*: Revise los detalles sobre la acción de restauración, escriba "restore" y seleccione *Restaurar*.


.Resultado
Astra Control Center restaura la aplicación en función de la información proporcionada. Si restauró la aplicación en un lugar, el contenido de cualquier volumen persistente existente se reemplaza por el contenido de los volúmenes persistentes de la aplicación restaurada.


NOTE: Después de una operación de protección de datos (clonado, backup, restauración) y un cambio de tamaño posterior de volumen persistente, se demora hasta veinte minutos antes de que se muestre el tamaño del nuevo volumen en la interfaz de usuario. La operación de protección de datos se realiza correctamente en cuestión de minutos, y se puede utilizar el software de gestión para el back-end de almacenamiento para confirmar el cambio de tamaño del volumen.
