---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Describe cómo retirar Astra Control Center y el operador Astra Control Center. 
---
= Desinstale Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Es posible que necesite eliminar los componentes de Astra Control Center si va a actualizar de una versión de prueba a una versión completa del producto. Para retirar el Centro de control Astra y el operador del Centro de control Astra, ejecute las instrucciones descritas en este procedimiento en secuencia.

.Lo que necesitará
* Utilice la interfaz de usuario de Astra Control Center para anular la gestión de todos link:../use/unmanage.html#stop-managing-compute["de clúster"].


.Pasos
. Eliminar Astra Control Center. El comando de ejemplo siguiente se basa en una instalación predeterminada. Modifique el comando si ha realizado configuraciones personalizadas.
+
[listing]
----
kubectl delete -f astra_control_center_min.yaml -n netapp-acc
----
+
Resultado:

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. Utilice el siguiente comando para eliminar la `netapp-acc` espacio de nombres:
+
[listing]
----
kubectl delete ns netapp-acc
----
+
Resultado:

+
[listing]
----
namespace "netapp-acc" deleted
----
. Utilice el siguiente comando para eliminar los componentes del sistema del operador de Astra Control Center:
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Resultado:

+
[listing]
----
namespace "netapp-acc-operator" deleted
customresourcedefinition.apiextensions.k8s.io "astracontrolcenters.astra.netapp.io" deleted
role.rbac.authorization.k8s.io "acc-operator-leader-election-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-manager-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-metrics-reader" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-proxy-role" deleted
rolebinding.rbac.authorization.k8s.io "acc-operator-leader-election-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-manager-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-proxy-rolebinding" deleted
configmap "acc-operator-manager-config" deleted
service "acc-operator-controller-manager-metrics-service" deleted
deployment.apps "acc-operator-controller-manager" deleted
----




== Obtenga más información

* link:../release-notes/known-issues.html["Problemas conocidos para la desinstalación"]

